language: python

cache: pip

python:
  - "3.6"
  - "3.7"
  - "3.8"
  - "3.9"

install:
  - pip install -r requirements_dev.txt

script:
  - make lint test BIN=""

deploy:
  provider: pypi
  username: "__token__"
  password: 
    secure: ?
  on:
    branch: master
    tags: true
