[tool.poetry]
name = "socceraction"
version = "1.1.1"
description = "Convert soccer event stream data to the SPADL format and value on-the-ball player actions"
authors = ["Tom Decroos <tom.decroos.be@gmail.com>", "Pieter Robberechts <pieter.robberechts@kuleuven.be>"]
license = "MIT"
readme = 'README.md'
repository = "https://github.com/ML-KULeuven/socceraction"
documentation = "https://socceraction.readthedocs.io"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent"
]

[tool.poetry.dependencies]
python = ">=3.7.1,<3.11"
pandas = "^1.3.3"
pandera = "^0.7.1"
numpy = "^1.21.2"
scikit-learn = "^0.24.2"
requests = "^2.26.0"
lxml = "^4.6.3"
Unidecode = "^1.3.2"

[tool.poetry.dev-dependencies]
black = "^21.9b0"
bumpversion = "^0.6.0"
flake8 = "^3.9.2"
mypy = "^0.910"
pydocstyle = "^6.1.1"
pylint = "^2.11.1"
pytest = "^6.2.5"
unify = "^0.5"
types-requests = "^2.25.8"
xgboost = "^1.4.2"
tables = "^3.6.1"
Sphinx = "^4.2.0"
furo = "^2021.9.22"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
